@startuml

title exercise 41 - Class Diagram


class App {
  +File input41
  +Scanner input
  void main()
}

class SiteBuilder {
  String siteName
  String siteAuthor
  String Path
  String create_dir(String path)
  String write_index(String name, String author, String path)
}

App <|-down- SiteBuilder: uses

@enduml